### ISSUE TITLE
自定义数据集训练pptsm当num_classes小于5时报错

### ISSUE THREAD

**Issue by thorory** [PaddlePaddle/PaddleVideo#188]
在尝试使用football action模型，在pptsm训练步骤中，由于自定义数据集的动作类别小于5，训练时报错，请问该情况如何解决？
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/nn/layer/norm.py:648: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    main()
  File "main.py", line 69, in main
    validate=args.validate)
  File "/home/work/paddlevideo/PaddleVideo/paddlevideo/tasks/train.py", line 114, in train_model
    outputs = model._layers.train_step(data)
  File "/home/work/paddlevideo/PaddleVideo/paddlevideo/modeling/framework/recognizers/recognizer2d.py", line 35, in train_step
    loss_metrics = self.head.loss(cls_score, labels)
  File "/home/work/paddlevideo/PaddleVideo/paddlevideo/modeling/heads/base.py", line 110, in loss
    top1a, top5a = self.get_acc(scores, labels_a, valid_mode)
  File "/home/work/paddlevideo/PaddleVideo/paddlevideo/modeling/heads/base.py", line 130, in get_acc
    top5 = paddle.metric.accuracy(input=scores, label=labels, k=5)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/paddle/metric/metrics.py", line 800, in accuracy
    topk_out, topk_indices = topk(input, k=k)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 5242, in topk
    out, indices = core.ops.top_k(input, 'k', _k)
ValueError: (InvalidArgument) input must have >= k columns
  [Hint: Expected input_dims[input_dims.size() - 1] >= k, but received input_dims[input_dims.size() - 1]:4 < k:5.] (at /paddle/paddle/fluid/operators/top_k_op.cc:48)
  [operator < top_k > error]

**Comment by omtrix** [comment]
因为main.py里面会计算top5的acc，如果你种类小于5的话，会导致相应行报错，解决方法是将包含top5的代码全部注释掉，只计算acc1

**Comment by thorory** [comment]
> 类小于5的话，会导致相应行报错，解决方法是将包含top5

已解决，谢谢

**Comment by thorory** [comment]
已解决

**Comment by Leon-Cheung-CQ** [comment]
> 已解决

请问应该注释什么地方呀，我的也是两个类别报相同的错。
