### ISSUE TITLE
pptsm 训练失败，报shape不匹配

### ISSUE THREAD

**Issue by omtrix** [PaddlePaddle/PaddleVideo#190]
数据采用ucf101/k400的frame形式，已在pptsm_k400_frames_uniform.yaml中调整相应参数。
运行python3.7 -B -m paddle.distributed.launch --gpus="0"  --log_dir=log_pptsm  main.py  --validate -c configs/recognition/pptsm/pptsm_k400_frames_uniform.yaml命令行，报错：
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    main()
  File "main.py", line 83, in main
    amp=args.amp)
  File "/home/hyj/桌面/master_projects/PaddleVideo-develop/paddlevideo/tasks/train.py", line 175, in train_model
    outputs = model(data, mode='train')
  File "/home/hyj/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hyj/桌面/master_projects/PaddleVideo-develop/paddlevideo/modeling/framework/recognizers/base.py", line 45, in forward
    return self.train_step(data_batch)
  File "/home/hyj/桌面/master_projects/PaddleVideo-develop/paddlevideo/modeling/framework/recognizers/recognizer2d.py", line 57, in train_step
    loss_metrics = self.head.loss(cls_score, labels)
  File "/home/hyj/桌面/master_projects/PaddleVideo-develop/paddlevideo/modeling/heads/base.py", line 98, in loss
    loss_a = self.label_smooth_loss(scores, labels_a, **kwargs)
  File "/home/hyj/桌面/master_projects/PaddleVideo-develop/paddlevideo/modeling/heads/base.py", line 119, in label_smooth_loss
    loss = self.loss_func(scores, labels, soft_label=True, **kwargs)
  File "/home/hyj/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hyj/桌面/master_projects/PaddleVideo-develop/paddlevideo/modeling/losses/base.py", line 49, in forward
    return self._forward(*args, **kwargs) * self.loss_weight
  File "/home/hyj/桌面/master_projects/PaddleVideo-develop/paddlevideo/modeling/losses/cross_entropy_loss.py", line 35, in _forward
    loss = F.cross_entropy(score, labels, **kwargs)
  File "/home/hyj/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 1392, in cross_entropy
    'use_softmax', use_softmax)
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:8 != labels_dims[i]:1.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:150)
  [operator < softmax_with_cross_entropy > error]
INFO 2021-08-28 10:48:46,318 launch_utils.py:327] terminate all the procs
ERROR 2021-08-28 10:48:46,318 launch_utils.py:584] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-08-28 10:48:49,321 launch_utils.py:327] terminate all the procs

在计算损失的时候，形状不匹配，我print形状，其中cls_score.shape=[8,num_classes],
labels =   [Tensor(shape=[1, 1], dtype=int64, place=CUDAPinnedPlace, stop_gradient=True,
       [[0]]), Tensor(shape=[1, 1], dtype=int64, place=CUDAPinnedPlace, stop_gradient=True,
       [[0]]), Tensor(shape=[1], dtype=float32, place=CUDAPinnedPlace, stop_gradient=True,
       [0.69980884])]
说实话有点看不懂这形状，想改但可能是这次paddle用了register之类的，我也不是很了解，都不知道源码在哪了
希望有大佬能给点建议，不论是报错 还是对于 @XXX ，abstract这类的代码问题。

**Comment by huangjun12** [comment]
cls_score的shape是[8,num_classes]
因为用了mix-up和label_smooth，label包含三个值：前两个是mix-up用到的两个batch的label，即两个标签，值为0；最后一个是mix-up时的权重因子，为float型的0.69。
源码在这： https://github.com/PaddlePaddle/PaddleVideo/blob/23d42dd463b3a6933abbc69bb375bbbef053558a/paddlevideo/modeling/heads/base.py#L92


如果只有一张卡的话，可以不用paddle.distributed.launch启动，单卡训练可以用：
```python
python3.7 main.py --validate -c configs/recognition/pptsm/pptsm_k400_frames_uniform.yaml
```

batch_size=8，label的第一维为1，是label的shape不对，是否修改了源码呢？
