### ISSUE TITLE
paddle2onnx:报错 There's 1 ops are not supported yet

### ISSUE THREAD

**Issue by 754467737** [PaddlePaddle/PaddleVideo#206]
Traceback (most recent call last):
  File "/home/wangnan/anaconda3/envs/action-py3.7/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/wangnan/anaconda3/envs/action-py3.7/lib/python3.7/site-packages/paddle2onnx/command.py", line 155, in main
    operator_export_type=operator_export_type)
  File "/home/wangnan/anaconda3/envs/action-py3.7/lib/python3.7/site-packages/paddle2onnx/command.py", line 122, in program2onnx
    operator_export_type=operator_export_type)
  File "/home/wangnan/anaconda3/envs/action-py3.7/lib/python3.7/site-packages/paddle2onnx/convert.py", line 79, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker, operator_export_type)
  File "/home/wangnan/anaconda3/envs/action-py3.7/lib/python3.7/site-packages/paddle2onnx/convert.py", line 33, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, operator_export_type, verbose)
  File "/home/wangnan/anaconda3/envs/action-py3.7/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 240, in build
    onnx_graph = ONNXGraph(paddle_graph, opset_version=opset_version, operator_export_type=operator_export_type)
  File "/home/wangnan/anaconda3/envs/action-py3.7/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 79, in __init__
    self.update_opset_version()
  File "/home/wangnan/anaconda3/envs/action-py3.7/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 194, in update_opset_version
    self.opset_version = OpMapper.get_recommend_opset_version(node_map, self.opset_version)
  File "/home/wangnan/anaconda3/envs/action-py3.7/lib/python3.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 127, in get_recommend_opset_version
    recommend_opset_version = OpMapper.check_support_status(node_map, opset_version, True)
  File "/home/wangnan/anaconda3/envs/action-py3.7/lib/python3.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 168, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError:
There's 1 ops are not supported yet
=========== temporal_shift ===========

temporal_shift不支持。
想请教下，怎么改才能让他支持，debug看了下temporal_shift函数，一直都是一些注册器，具体内容看的眼花缭乱！求救！help!

**Comment by 754467737** [comment]
或者说，我是否可以以TSM代码中用pytorch写的temporal_shift部分，替换到paddle2onnx这里不支持的部分？两个是否可以混用？

**Comment by blue-q** [comment]
> 或者说，我是否可以以TSM代码中用pytorch写的temporal_shift部分，替换到paddle2onnx这里不支持的部分？两个是否可以混用？

您好，请问您解决这个问题了吗

**Comment by 754467737** [comment]
最新版本好像已经解决这个问题了，2.4还是多少版本，我忘了，很久没动了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleVideo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月13日(星期二) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleVideo] paddle2onnx:报错 There's 1 ops are not supported yet (#206)





  
或者说，我是否可以以TSM代码中用pytorch写的temporal_shift部分，替换到paddle2onnx这里不支持的部分？两个是否可以混用？
  
您好，请问您解决这个问题了吗

**Comment by blue-q** [comment]
> 最新版本好像已经解决这个问题了，2.4还是多少版本，我忘了，很久没动了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleVideo" ***@***.***&gt;; 发送时间:&nbsp;2022年12月13日(星期二) 下午5:03 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleVideo] paddle2onnx:报错 There's 1 ops are not supported yet (#206) 或者说，我是否可以以TSM代码中用pytorch写的temporal_shift部分，替换到paddle2onnx这里不支持的部分？两个是否可以混用？ 您好，请问您解决这个问题了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

刚才我试了一下paddle2.4.1好像也存在这个问题

**Comment by imchenmin** [comment]
有解决嘛？

**Comment by luyao-cv** [comment]
请尝试最新版本，>2.5.1
