### ISSUE TITLE
Pipeline 不是顺序执行的？

### ISSUE THREAD

**Issue by CuberrChen** [PaddlePaddle/PaddleVideo#216]
请问Pipeline下的transform不是顺序执行的吗？

我在自定义某些transform后，前后数据有依赖关系。但是出现后面的transform并没有获取到前面的transform变换后的数据的情况，造成报错。

我的数据处理顺序如下：

```
[10/01 22:07:41]         sample : 
[10/01 22:07:41]             name : AutoPadding
[10/01 22:07:41]             window_size : 350
[10/01 22:07:41]         transform : 
[10/01 22:07:41]             Pose3dTrans : None
[10/01 22:07:41]             PoseCompact : 
[10/01 22:07:41]                 allow_imgpad : True
[10/01 22:07:41]                 hw_ratio : 1.0
[10/01 22:07:41]             Resize : 
[10/01 22:07:41]                 scale : [-1, 64]
[10/01 22:07:41]             RandomResizedCrop : 
[10/01 22:07:41]                 area_range : [0.56, 1.0]
[10/01 22:07:41]             Resize : 
[10/01 22:07:41]                 keep_ratio : False
[10/01 22:07:41]                 scale : [56, 56]

```
报错信息：
```
<paddlevideo.loader.pipelines.skeleton_pipeline.AutoPadding object at 0x7f70946d0090>
<paddlevideo.loader.pipelines.skeleton_pipeline.AutoPadding object at 0x7f70946d0090>
<paddlevideo.loader.pipelines.skeleton_pipeline.AutoPadding object at 0x7f70946d0090>
<paddlevideo.loader.pipelines.skeleton_pipeline.AutoPadding object at 0x7f70946d0090>
<paddlevideo.loader.pipelines.skeleton_pipeline.Pose3dTrans object at 0x7f70946d00d0>
<paddlevideo.loader.pipelines.augmentations.PoseCompact object at 0x7f70946d0050>
<paddlevideo.loader.pipelines.augmentations.Resize object at 0x7f70946d0150>
**[10/01 22:07:45] fail to perform transform [<paddlevideo.loader.pipelines.augmentations.Resize object at 0x7f70946d0150>] with error: 'crop_quadruple' and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleVideo/paddlevideo/loader/pipelines/compose.py", line 70, in __call__
    data = p(data)
  File "/home/aistudio/PaddleVideo/paddlevideo/loader/pipelines/augmentations.py", line 255, in __call__
    crop_quadruple = results['crop_quadruple']
KeyError: 'crop_quadruple'**

<paddlevideo.loader.pipelines.skeleton_pipeline.AutoPadding object at 0x7f70946d0090>
ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    main()
  File "main.py", line 83, in main
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 391, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _get_data
    batch.reraise()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise
    raise self.exc_type(msg)
KeyError: 'DataLoader worker(1) caught KeyError with message:\nTraceback (most recent call last):\n  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 320, in _worker_loop\n    batch = fetcher.fetch(indices)\n  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 106, in fetch\n    data = [self.dataset[idx] for idx in batch_indices]\n  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 106, in <listcomp>\n    data = [self.dataset[idx] for idx in batch_indices]\n  File "/home/aistudio/PaddleVideo/paddlevideo/loader/dataset/base.py", line 80, in __getitem__\n    return self.prepare_train(idx)\n  File "/home/aistudio/PaddleVideo/paddlevideo/loader/dataset/posec3d_dataset.py", line 65, in prepare_train\n    results = self.pipeline(results)\n  File "/home/aistudio/PaddleVideo/paddlevideo/loader/pipelines/compose.py", line 76, in __call__\n    raise e\n  File "/home/aistudio/PaddleVideo/paddlevideo/loader/pipelines/compose.py", line 70, in __call__\n    data = p(data)\n  File "/home/aistudio/PaddleVideo/paddlevideo/loader/pipelines/augmentations.py", line 255, in __call__\n    crop_quadruple = results[\'crop_quadruple\']\nKeyError: \'crop_quadruple\'\n'

    amp=args.amp)
  File "/home/aistudio/PaddleVideo/paddlevideo/tasks/train.py", line 157, in train_model
<paddlevideo.loader.pipelines.skeleton_pipeline.Pose3dTrans object at 0x7f70946d00d0>
    for i, data in enumerate(train_loader):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
<paddlevideo.loader.pipelines.augmentations.PoseCompact object at 0x7f70946d0050>
<paddlevideo.loader.pipelines.skeleton_pipeline.Pose3dTrans object at 0x7f70946d00d0>
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

<paddlevideo.loader.pipelines.augmentations.PoseCompact object at 0x7f70946d0050>
<paddlevideo.loader.pipelines.augmentations.Resize object at 0x7f70946d0150>
<paddlevideo.loader.pipelines.augmentations.Resize object at 0x7f70946d0150>
```

上面我打印了pipeline，可以看到不是顺序的？从报错信息来看，后面的Resize没有接受的数据中没有crop_quadruple这个数据，但是实际上在前面的PoseCompact中我已经存到了字典中并返回了。

**Comment by CuberrChen** [comment]
找到错误。抱歉。

**Comment by 754467737** [comment]
我也出现这个问题，请问错在哪？
