### ISSUE TITLE
项目存在一个BUG，训练自己的2个类会报错

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleVideo#304]
使用pptsm_k400_videos_uniform.yaml这个配置，我只有2个类别会报错：
/home/fut/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/nn/layer/norm.py:652: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    main()
  File "main.py", line 84, in main
    train_model(cfg,
  File "/home/fut/paddle/PaddleVideo-release-2.1.1/paddlevideo/tasks/train.py", line 183, in train_model
    outputs = model(data, mode='train')
  File "/home/fut/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/fut/paddle/PaddleVideo-release-2.1.1/paddlevideo/modeling/framework/recognizers/base.py", line 45, in forward
    return self.train_step(data_batch)
  File "/home/fut/paddle/PaddleVideo-release-2.1.1/paddlevideo/modeling/framework/recognizers/recognizer2d.py", line 47, in train_step
    loss_metrics = self.head.loss(cls_score, labels)
  File "/home/fut/paddle/PaddleVideo-release-2.1.1/paddlevideo/modeling/heads/base.py", line 104, in loss
    top1a, top5a = self.get_acc(scores, labels_a, valid_mode)
  File "/home/fut/paddle/PaddleVideo-release-2.1.1/paddlevideo/modeling/heads/base.py", line 124, in get_acc
    top5 = paddle.metric.accuracy(input=scores, label=labels, k=5)
  File "/home/fut/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/metric/metrics.py", line 800, in accuracy
    topk_out, topk_indices = paddle.topk(input, k=k)
  File "/home/fut/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/tensor/search.py", line 737, in topk
    out, indices = _C_ops.top_k_v2(x, 'k',
ValueError: (InvalidArgument) input of topk op must have >= 5 columns in axis of 1
  [Hint: Expected input_dims[axis] >= k, but received input_dims[axis]:2 < k:5.] (at /paddle/paddle/fluid/operators/top_k_v2_op.cc:63)
  [operator < top_k_v2 > error]
其中num_classes: 2我改成2类别就报错，但是我改回400就不错了

**Comment by huangjun12** [comment]
因为算精度的时候会算top5，如果只有2类，没办法计算top5指标，所以会报错。

如果训练2个类别，可以把计算top5部分的代码注释掉
