### ISSUE TITLE
pptsm 模型推理时报错

### ISSUE THREAD

**Issue by zidingyi-wangda** [PaddlePaddle/PaddleVideo#384]
加载从
https://bj.bcebos.com/acg-algo/PaddleVideo_application/VideoQualityAssessment/ppTSM.pdparams
下载的预训练模型推理时，报
OSError: {weight_path} is not a checkpoint file
错误，该如何解决？

**Comment by huangjun12** [comment]
看报错可能是路径设置不对

可以参考文档check下哈：
https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/recognition/pp-tsm.md#模型推理

**Comment by geekchen007** [comment]
https://bj.bcebos.com/acg-algo/PaddleVideo_application/VideoQualityAssessment/ppTSM.pdparams
ValueError: `paddle.load` can not parse the file:pretrained_dygraph/ppTSM.pdparams.
已经排除路径错误。
Debug信息：
- 预训练模型是140M，自己从头train的model是89.9M。
环境：
- paddlepaddle-gpu          2.2.2           py37_gpu_cuda10.1_many_linux

**Comment by geekchen007** [comment]
参考文档的预训练模型可用
[https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/recognition/pp-tsm.md#模型推理]

**Comment by aureosun** [comment]
@geekchen007 @huangjun12 
在按照 https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/recognition/pp-tsm.md#44
运行大佬的demo时候，在6模型推理，导出推理模型正常，运行 基于python预测引擎推理 时，报错

python tools/predict.py --input_file data/example.avi --config configs/recognition/pptsm/v2/pptsm_lcnet_k400_16frames_uniform_dml_distillation.yaml --model_file inference/PPTSMv2/PPTSMv2.pdmodel --params_file inference/PPTSMv2/PPTSMv2.pdiparams --use_gpu=False --use_tensorrt=False
Warning! No module named 'imageio', [imageio] package and it's dependencies is required for VideoSwin.
D:\Hand\PaddleVideo\paddlevideo\loader\pipelines\augmentations_ava.py:24: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
D:\Hand\PaddleVideo\paddlevideo\loader\pipelines\augmentations_ava.py:25: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
D:\Hand\PaddleVideo\paddlevideo\loader\pipelines\augmentations_ava.py:26: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
D:\Hand\PaddleVideo\paddlevideo\loader\pipelines\augmentations_ava.py:27: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
D:\Hand\PaddleVideo\paddlevideo\loader\pipelines\augmentations_ava.py:28: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
D:\Hand\PaddleVideo\paddlevideo\loader\pipelines\augmentations_ava.py:29: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
Warning! No module named 'skimage', [scikit-image] package and it's dependencies is required for ADDS.
Warning! No module named 'paddlenlp', [paddlenlp] package and it's dependencies is required for ActBERT.
Warning! No module named 'SimpleITK', [SimpleITK] package and it's dependencies is required for PP-Care.
Warning! No module named 'SimpleITK', [SimpleITK] package and it's dependencies is required for PP-Care.
Warning! No module named 'lmdb', [lmdb] package and it's dependencies is required for ActBERT.
Warning! No module named 'paddlenlp', [paddlenlp] package and it's dependencies is required for ActBERT.
Warning! No module named 'lmdb', [lmdb] package and it's dependencies is required for ActBERT.
Warning! No module named 'paddlenlp', [paddlenlp] package and it's dependencies is required for ActBERT.
Traceback (most recent call last):
  File "D:\Hand\PaddleVideo\tools\predict.py", line 22, in <module>
    from utils import build_inference_helper
  File "D:\Hand\PaddleVideo\tools\utils.py", line 60, in <module>
    from tools.ava_predict import (detection_inference, frame_extraction,
ModuleNotFoundError: No module named 'tools.ava_predict'

核查之后发现路径什么的都是对的，求问怎么解决
