### ISSUE TITLE
运行demo会有问题

### ISSUE THREAD

**Issue by jermycc** [PaddlePaddle/PaddleVideo#421]
按照官方给的st-gcn的demo一步一步运行，但是训练的时候会遇到报错，请问应该怎么解决呢：
No module named 'SimpleITK', [SimpleITK] package and it's dependencies is required for PP-Care.
No module named 'SimpleITK', [SimpleITK] package and it's dependencies is required for PP-Care.
No module named 'lmdb', [lmdb] package and it's dependencies is required for ActBERT.
No module named 'lmdb', [lmdb] package and it's dependencies is required for ActBERT.
[05/04 09:57:26] DALI is not installed, you can improve performance if use DALI
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    from paddlevideo.tasks import (test_model, train_dali, train_model,
  File "/home/aistudio/work/PaddleVideo/paddlevideo/tasks/__init__.py", line 15, in <module>
    from .train import train_model
  File "/home/aistudio/work/PaddleVideo/paddlevideo/tasks/train.py", line 27, in <module>
    from ..modeling.builder import build_model
  File "/home/aistudio/work/PaddleVideo/paddlevideo/modeling/__init__.py", line 16, in <module>
    from .backbones import ResNet
  File "/home/aistudio/work/PaddleVideo/paddlevideo/modeling/backbones/__init__.py", line 21, in <module>
    from .movinet import MoViNet
  File "/home/aistudio/work/PaddleVideo/paddlevideo/modeling/backbones/movinet.py", line 8, in <module>
    from paddle.nn.layer import Identity
ImportError: cannot import name 'Identity' from 'paddle.nn.layer' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/__init__.py)

**Comment by huangjun12** [comment]
paddle版本是多少呢

**Comment by jermycc** [comment]
环境配置
Python版本
python 3.7

框架版本
PaddlePaddle 2.1.2







陈敬逸
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleVideo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleVideo] 运行demo会有问题 (Issue #421)





 
paddle版本是多少呢

**Comment by huangjun12** [comment]
paddle 版本建议升级成2.2，Identity是2.2新增的API

安装参考： https://www.paddlepaddle.org.cn

**Comment by jermycc** [comment]
已经可以运行，最近在复现“2021 CCF BDCI基于飞桨实现花样滑冰选手骨骼点动作识别”，请问可以分享A榜和B榜的测试集答案，以做验证吗？十分感谢！




陈敬逸
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleVideo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月6日(星期五) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleVideo] 运行demo会有问题 (Issue #421)





 
paddle 版本建议升级成2.2，Identity是2.2新增的API
 
安装参考： https://www.paddlepaddle.org.cn

**Comment by onedayCVPR** [comment]
安装官方给的 [PaddleVideo](https://github.com/PaddlePaddle/PaddleVideo)/[applications](https://github.com/PaddlePaddle/PaddleVideo/tree/develop/applications)/[TableTennis](https://github.com/PaddlePaddle/PaddleVideo/tree/develop/applications/TableTennis)/ActionRecognition/
下的模型训练 启动训练 命令：
python3.7 -u main.py --amp --validate -c applications/TableTennis/ActionRecognition/configs/videoswin_tabletennis.yaml
报错如下
[06/20 16:39:05] Using gradient accumulation training strategy, global_batch_size=64, num_gpus=1, num_accumulative_iters=64
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    main()
  File "main.py", line 135, in main
    profiler_options=args.profiler_options)
  File "/home/helloyyptable/paddleT/PaddleVideo/paddlevideo/tasks/train.py", line 100, in train_model
    model = build_model(cfg.MODEL)
  File "/home/helloyyptable/paddleT/PaddleVideo/paddlevideo/utils/config.py", line 25, in __getattr__
    return self[key]
KeyError: 'MODEL'
