### ISSUE TITLE
文本識別預測報錯 RestNet50+SRN算法

### ISSUE THREAD

**Issue by jolinchao** [PaddlePaddle/PaddleVideo#427]
想詢問識別模型報錯問題

**Comment by jolinchao** [comment]
import imp, sys, os
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: '0'
heter_devices:
heter_worker_num: None
heter_workers:
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers:
training_script: tools/eval.py
training_script_args: ['-c', 'configs/rec/rec_r50_fpn_srn.yml', '-o', 'Global.checkpoints=output/rec/srn_r50/best_accuracy']
worker_num: None
workers:
------------------------------------------------
WARNING 2022-05-11 15:54:21,680 launch.py:423] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2022-05-11 15:54:21,680 launch_utils.py:529] Local start 1 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                                                 |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                                               |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:56892                      |
    |                     PADDLE_TRAINERS_NUM                        1                                          |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:56892                      |
    |                     PADDLE_RANK_IN_NODE                        0                                          |
    |                 PADDLE_LOCAL_DEVICE_IDS                       '0'                                         |
    |                 PADDLE_WORLD_DEVICE_IDS                       '0'                                       |
    |                     FLAGS_selected_gpus                       '0'                                                |
    |             FLAGS_selected_accelerators                       '0'                                             |
    +=======================================================================================+

INFO 2022-05-11 15:54:21,680 launch_utils.py:532] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
子目錄或檔案 -p 已經存在。
處理時發生錯誤: -p。
子目錄或檔案 log 已經存在。
處理時發生錯誤: log。
'rm' 不是內部或外部命令、可執行的程式或批次檔。
launch proc_id:11884 idx:0
C:\Python3.6\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
Traceback (most recent call last):
  File "tools/eval.py", line 26, in <module>
    from ppocr.data import build_dataloader
  File "D:\JolinChao\00_OperatingEnvi\Anaconda3\envs\paddle_env\PaddleOCR\ppocr\data\__init__.py", line 23, in <module>
    import paddle
  File "C:\Python3.6\lib\site-packages\paddle\__init__.py", line 293, in <module>
    from .hapi import Model  # noqa: F401
  File "C:\Python3.6\lib\site-packages\paddle\hapi\__init__.py", line 25, in <module>
    logger.setup_logger()
  File "C:\Python3.6\lib\site-packages\paddle\hapi\logger.py", line 47, in setup_logger
    local_rank = ParallelEnv().local_rank
  File "C:\Python3.6\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 121, in __init__
    self._device_id = int(selected_gpus[0])
ValueError: invalid literal for int() with base 10: "'0'"
INFO 2022-05-11 15:54:27,773 launch_utils.py:341] terminate all the procs
ERROR 2022-05-11 15:54:27,773 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-05-11 15:54:30,788 launch_utils.py:341] terminate all the procs
INFO 2022-05-11 15:54:30,788 launch.py:311] Local processes completed.

**Comment by jolinchao** [comment]
> _No description provided._



> _No description provided._
