### ISSUE TITLE
PPHuman训练出现错误

### ISSUE THREAD

**Issue by MrFaith2001** [PaddlePaddle/PaddleVideo#429]
当进行到PPHuman教程的训练阶段时:
`python main.py -c applications/PPHuman/configs/stgcn_pphuman.yaml`
会出现如下报错:
```
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    main()
  File "main.py", line 135, in main
    profiler_options=args.profiler_options)
  File "/home/aistudio/PaddleVideo-develop/paddlevideo/tasks/train.py", line 272, in train_model
    record_list["batch_time"].sum)
ZeroDivisionError: division by zero
```
Paddle:2.2.2
PaddleVedio:develop
PaddleDetection:2.4.0

**Comment by zoooo0820** [comment]
请检查一下设置的batchsize大小和数据集本身的数量呢

**Comment by xuyao91** [comment]
是的，我的数据量太少，也报这个错，把batch_size改小点就好了。
