### ISSUE TITLE
[MultimodalVideoTag]:修改参数后，训练时报"模型和参数的维度不匹配",请问这种常见的情况在paddlepaddle应该如何处理呢

### ISSUE THREAD

**Issue by aiot-tech** [PaddlePaddle/PaddleVideo#436]
```Traceback (most recent call last):
  File "scenario_lib/train.py", line 262, in <module>
    train(args)
  File "scenario_lib/train.py", line 197, in train
    train_model.load_test_weights_file(exe, args.pretrain, train_prog, place)
  File "MultimodalVideoTag/scenario_lib/models/attention_lstm_ernie.py", line 410, in load_test_weights_file
    filename="param")
  File "/python3.7/site-packages/paddle/fluid/io.py", line 976, in load_vars
    format(orig_shape, each_var.name, new_shape))
RuntimeError: Variable's shape does not match, the Program requires a parameter with the shape of ((2048, 200)), while the loaded parameter (namely [ fc_76.w_0 ]) has a shape of  ((2048, 110)).
```
查看了官方的相关文档，发现paddlepaddle的很多文档都相当不全，且没有针对具体的问题给出解决方案的样例，让人非常困惑

**Comment by huangjun12** [comment]
是类别由200改成110了吗
改一下配置文件里的类别数量num_class呢？

**Comment by aiot-tech** [comment]
是将原有的110类改为200类，结果预训练权重维度和模型维度匹配不上，有相关的解决方法吗

**Comment by aiot-tech** [comment]
`https://github.com/PaddlePaddle/PaddleVideo/blob/develop/applications/MultimodalVideoTag/scenario_lib/utils.py#L174` 这里报错，官方文档只有`fluid.io.load_vars`的基本描述，具体的解决方案是没有的。这种常见的问题后续会考虑添加自动处理功能吗，谢谢

**Comment by aiot-tech** [comment]
你好，如果想把param参数文件里的部分参数(如除去最后一层的参数)加载到模型中，该如何处理呢
```
def load_test_weights_file(self, exe, weights, prog, place):
   """
   load_test_weights_file
   """
   load_vars = [x for x in prog.list_vars() \
                if isinstance(x, fluid.framework.Parameter)]
   load_vars = list(filter(lambda x: "fc_76" not in x.name, load_vars))  # 

   fluid.io.load_vars(exe,
                      dirname=weights,
                      vars=load_vars,
                      filename="param")
```
以上是我尝试的代码，但对缺失的那部分参数paddle会报错，针对这种预训练场景，paddle有没有相关的文档？

**Comment by aiot-tech** [comment]
已通过paddle主repo得以解决，close了哈，后续期望官方能出一些使得paddle更易用的、有关于静态图的详细文档

**Comment by kycgssss** [comment]
我也遇到了和你一样的问题，能分享一下具体的解决方式

> 已通过paddle主repo得以解决，close了哈，后续期望官方能出一些使得paddle更易用的、有关于静态图的详细文档

**Comment by kycgssss** [comment]
您好，我也遇到了和你一样的问题，能分享一下具体的解决方式吗

> 已通过paddle主repo得以解决，close了哈，后续期望官方能出一些使得paddle更易用的、有关于静态图的详细文档
