### ISSUE TITLE
predict_onnx.py  input error index: 1 Got: 60 Expected: 6

### ISSUE THREAD

**Issue by chennankuan** [PaddlePaddle/PaddleVideo#511]
Traceback (most recent call last):
  File "deploy/paddle2onnx/predict_onnx.py", line 174, in <module>
    main()
  File "deploy/paddle2onnx/predict_onnx.py", line 154, in main
    input_feed={input_names: batched_inputs[0]})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: data_batch_0 for the following indices
 index: 1 Got: 60 Expected: 6
 Please fix either the inputs or the model

**Comment by HydrogenSulfate** [comment]
可以确认一下你图片输入维度的shape[1]是多少，看报错信息你的shape[1]是60，而网络需要的shape[1]是6
