### ISSUE TITLE
football project, 我导出了lstm模型，在precdict时候报错，但用checkpoint里面的模型却能运行，不知道为啥

### ISSUE THREAD

**Issue by freeman-1995** [PaddlePaddle/PaddleVideo#515]
Traceback (most recent call last):
  File "predict.py", line 28, in <module>
    bmn_results, action_results = model_predict.infer(imgs_path, pcm_path)
  File "action_detect/action.py", line 37, in timer
    retval = func(*args)
  File "action_detect/action.py", line 104, in infer
    action_results = self.video_classify(material)
  File "action_detect/action.py", line 37, in timer
    retval = func(*args)
  File "action_detect/action.py", line 113, in video_classify
    action_results = self.classify_model.predict(self.configs, material=material)
  File "action_detect/models/lstm_infer.py", line 97, in predict
    output1, output2 = self.infer(input1_arr, input1_lod, input2_arr, input2_lod)
  File "action_detect/models/lstm_infer.py", line 65, in infer
    self.predictor.run()
ValueError: In user code:
InvalidArgumentError: The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 2, axis's size is 3
      [Hint: Expected x_rank == axis_size, but received x_rank:2 != axis_size:3.] (at /paddle/paddle/fluid/operators/transpose_op.cc:47)
      [operator < transpose2 > error]

**Comment by littlerookie** [comment]
一样的报错，请问您解决了吗？

**Comment by lxz-dream** [comment]
我也遇见了一样的问题，请问你们解决了吗

**Comment by jerrywgz** [comment]
您好，请问问题还是否需要解决，目前多模态视频能力集成在PaddleMIX中，https://github.com/PaddlePaddle/PaddleMIX/tree/develop 可以在这个repo下提出您的需求

**Comment by dxlei** [comment]
请问解决了吗？
