### ISSUE TITLE
summery flops计算 error

### ISSUE THREAD

**Issue by chennankuan** [PaddlePaddle/PaddleVideo#519]
aistudio@jupyter-553592-4405729:~/PaddleVideo-develop_lastest$ python ./tools/summary.py 
Traceback (most recent call last):
  File "./tools/summary.py", line 23, in <module>
    import paddleslim
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/__init__.py", line 17, in <module>
    from paddleslim import prune
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/__init__.py", line 16, in <module>
    from .pruner import *
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/pruner.py", line 20, in <module>
    from ..core import VarWrapper, OpWrapper, GraphWrapper
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/__init__.py", line 19, in <module>
    from ..core import dygraph
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/dygraph.py", line 7, in <module>
    from paddle.fluid.dygraph.base import program_desc_tracing_guard, _switch_declarative_mode_guard_
ImportError: cannot import name '_switch_declarative_mode_guard_' from 'paddle.fluid.dygraph.base' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py)

**Comment by jerrywgz** [comment]
您好，请问问题还是否需要解决，目前多模态视频能力集成在PaddleMIX中，https://github.com/PaddlePaddle/PaddleMIX/tree/develop 可以在这个repo下提出您的需求
