### ISSUE TITLE
slowfast +faster RCNN 进行推理时报错不存在txt

### ISSUE THREAD

**Issue by Deill2** [PaddlePaddle/PaddleVideo#552]
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00252.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00256.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00260.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00264.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00268.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00272.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00276.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00280.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00284.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00288.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00292.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00296.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00300.jpg
[11/11 21:49:08] ppdet.engine INFO: Detection bbox results save in tmp_detection\00304.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00308.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00312.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00316.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00320.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00324.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00328.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00332.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00336.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00340.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00344.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00348.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00352.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00356.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00360.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00364.jpg
[11/11 21:49:09] ppdet.engine INFO: Detection bbox results save in tmp_detection\00368.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00372.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00376.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00380.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00384.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00388.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00392.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00396.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00400.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00404.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00408.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00412.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00416.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00420.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00424.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00428.jpg
[11/11 21:49:10] ppdet.engine INFO: Detection bbox results save in tmp_detection\00432.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00436.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00440.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00444.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00448.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00452.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00456.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00460.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00464.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00468.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00472.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00476.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00480.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00484.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00488.jpg
[11/11 21:49:11] ppdet.engine INFO: Detection bbox results save in tmp_detection\00492.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00496.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00500.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00504.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00508.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00512.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00516.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00520.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00524.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00528.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00532.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00536.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00540.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00544.jpg
[11/11 21:49:12] ppdet.engine INFO: Detection bbox results save in tmp_detection\00548.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00552.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00556.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00560.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00564.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00568.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00572.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00576.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00580.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00584.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00588.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00592.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00596.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00600.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00604.jpg
[11/11 21:49:13] ppdet.engine INFO: Detection bbox results save in tmp_detection\00608.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00612.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00616.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00620.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00624.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00628.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00632.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00636.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00640.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00644.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00648.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00652.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00656.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00660.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00664.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00668.jpg
[11/11 21:49:14] ppdet.engine INFO: Detection bbox results save in tmp_detection\00672.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00676.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00680.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00684.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00688.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00692.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00696.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00700.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00704.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00708.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00712.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00716.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00720.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00724.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00728.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00732.jpg
[11/11 21:49:15] ppdet.engine INFO: Detection bbox results save in tmp_detection\00736.jpg
[11/11 21:49:16] ppdet.engine INFO: Detection bbox results save in tmp_detection\00740.jpg
[11/11 21:49:16] ppdet.engine INFO: Detection bbox results save in tmp_detection\00744.jpg
[11/11 21:49:16] ppdet.engine INFO: Detection bbox results save in tmp_detection\00748.jpg
[11/11 21:49:16] ppdet.engine INFO: Detection bbox results save in tmp_detection\00752.jpg
[11/11 21:49:16] ppdet.engine INFO: Detection bbox results save in tmp_detection\00756.jpg
[11/11 21:49:16] ppdet.engine INFO: Detection bbox results save in tmp_detection\00760.jpg
[11/11 21:49:16] ppdet.engine INFO: Detection bbox results save in tmp_detection\00764.jpg
Traceback (most recent call last):
  File "D:/project/classWanZhou/PaddleVideo-develop/tools/predict.py", line 327, in <module>
    main()
  File "D:/project/classWanZhou/PaddleVideo-develop/tools/predict.py", line 203, in main
    inputs = InferenceHelper.preprocess(file)
  File "D:\project\classWanZhou\PaddleVideo-develop\tools\utils.py", line 1365, in preprocess
    proposals, scores = get_detection_result(
  File "D:\project\classWanZhou\PaddleVideo-develop\tools\ava_predict.py", line 313, in get_detection_result
    with open(txt_file_path, 'r') as detection_file:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp_detection\\00032.txt'
finish object detection

**Comment by Deill2** [comment]
python tools/predict.py    -c configs/detection/ava/ava_class.yaml     --input_file "D:/project/classWanZhou/yolo_slowfast-master/demo/1.avi"     --model_file "inference_output/AVA_SlowFast_FastRcnn.pdmodel"  --params_file "inference_output/AVA_SlowFast_FastRcnn.pdiparams"   --use_gpu=True   --use_tensorrt=False

**Comment by huangjun12** [comment]
看日志是没有 00032.jpg，检查下文件路径吧
