### ISSUE TITLE
AttributeError: 'VisionTransformer' object has no attribute 'seg_num'

### ISSUE THREAD

**Issue by yxs96** [PaddlePaddle/PaddleVideo#569]
请教各位，训练过程没问题，测试报属性错误：

$ CUDA_VISIBLE_DEVICES=3 python main.py -c applications/PP-Care/configs/timesformer_MRI.yaml --test -w "./output/TimeSformer_MRI/TimeSformer_MRI_best.pdparams" 
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:24: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:25: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:26: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:27: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:28: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:29: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
Warning! No module named 'paddlenlp', [paddlenlp] package and it's dependencies is required for ActBERT.
Warning! No module named 'lmdb', [lmdb] package and it's dependencies is required for ActBERT.
Warning! No module named 'paddlenlp', [paddlenlp] package and it's dependencies is required for ActBERT.
Warning! No module named 'lmdb', [lmdb] package and it's dependencies is required for ActBERT.
Warning! No module named 'paddlenlp', [paddlenlp] package and it's dependencies is required for ActBERT.
[01/26 16:17:00] DATASET : 
[01/26 16:17:00]     batch_size : 4
[01/26 16:17:00]     num_workers : 4
[01/26 16:17:00]     test : 
[01/26 16:17:00]         data_prefix : 
[01/26 16:17:00]         file_path : /home/yxs/PaddleVideo-develop/data/PP-Care/datasets/AV133/test_res2.txt
[01/26 16:17:00]         format : MRIDataset
[01/26 16:17:00]     test_batch_size : 8
[01/26 16:17:00]     train : 
[01/26 16:17:00]         data_prefix : 
[01/26 16:17:00]         file_path : /home/yxs/PaddleVideo-develop/data/PP-Care/datasets/AV133/train_res2.txt
[01/26 16:17:00]         format : MRIDataset
[01/26 16:17:00]     valid : 
[01/26 16:17:00]         data_prefix : 
[01/26 16:17:00]         file_path : /home/yxs/PaddleVideo-develop/data/PP-Care/datasets/AV133/test_res2.txt
[01/26 16:17:00]         format : MRIDataset
[01/26 16:17:00] ------------------------------------------------------------
[01/26 16:17:00] GRADIENT_ACCUMULATION : 
[01/26 16:17:00]     global_batch_size : 64
[01/26 16:17:00] ------------------------------------------------------------
[01/26 16:17:00] METRIC : 
[01/26 16:17:00]     name : CenterCropMetric_MRI
[01/26 16:17:00] ------------------------------------------------------------
[01/26 16:17:00] MODEL : 
[01/26 16:17:00]     backbone : 
[01/26 16:17:00]         attention_type : divided_space_time
[01/26 16:17:00]         depth : 12
[01/26 16:17:00]         embed_dim : 768
[01/26 16:17:00]         epsilon : 1e-06
[01/26 16:17:00]         img_size : 224
[01/26 16:17:00]         in_channels : 1
[01/26 16:17:00]         mlp_ratio : 4
[01/26 16:17:00]         name : VisionTransformer
[01/26 16:17:00]         num_heads : 12
[01/26 16:17:00]         patch_size : 16
[01/26 16:17:00]         pretrained : /home/yxs/PaddleVideo-develop/data/PP-Care/ViT_base_patch16_224_pretrained.pdparams
[01/26 16:17:00]         qkv_bias : True
[01/26 16:17:00]         seg_num : 8
[01/26 16:17:00]     framework : RecognizerTransformer_MRI
[01/26 16:17:00]     head : 
[01/26 16:17:00]         in_channels : 768
[01/26 16:17:00]         name : TimeSformerHead
[01/26 16:17:00]         num_classes : 2
[01/26 16:17:00]         std : 0.02
[01/26 16:17:00] ------------------------------------------------------------
[01/26 16:17:00] OPTIMIZER : 
[01/26 16:17:00]     learning_rate : 
[01/26 16:17:00]         gamma : 0.9
[01/26 16:17:00]         learning_rate : 0.005
[01/26 16:17:00]         milestones : [20, 29]
[01/26 16:17:00]         name : MultiStepDecay
[01/26 16:17:00]     name : Adam
[01/26 16:17:00]     weight_decay : 
[01/26 16:17:00]         name : L2
[01/26 16:17:00]         value : 5e-05
[01/26 16:17:00] ------------------------------------------------------------
[01/26 16:17:00] PIPELINE : 
[01/26 16:17:00]     test : 
[01/26 16:17:00]         decode : 
[01/26 16:17:00]             name : MRIDecoder
[01/26 16:17:00]         sample : 
[01/26 16:17:00]             linspace_sample : True
[01/26 16:17:00]             name : Sampler
[01/26 16:17:00]             num_seg : 8
[01/26 16:17:00]             seg_len : 1
[01/26 16:17:00]             valid_mode : True
[01/26 16:17:00]     train : 
[01/26 16:17:00]         decode : 
[01/26 16:17:00]             name : MRIDecoder
[01/26 16:17:00]         sample : 
[01/26 16:17:00]             linspace_sample : True
[01/26 16:17:00]             name : Sampler
[01/26 16:17:00]             num_seg : 8
[01/26 16:17:00]             seg_len : 1
[01/26 16:17:00]             valid_mode : False
[01/26 16:17:00]     valid : 
[01/26 16:17:00]         decode : 
[01/26 16:17:00]             name : MRIDecoder
[01/26 16:17:00]         sample : 
[01/26 16:17:00]             linspace_sample : True
[01/26 16:17:00]             name : Sampler
[01/26 16:17:00]             num_seg : 8
[01/26 16:17:00]             seg_len : 1
[01/26 16:17:00]             valid_mode : False
[01/26 16:17:00] ------------------------------------------------------------
[01/26 16:17:00] epochs : 30
[01/26 16:17:00] log_interval : 20
[01/26 16:17:00] log_level : INFO
[01/26 16:17:00] model_name : TimeSformer_MRI
[01/26 16:17:00] save_interval : 5
W0126 16:17:00.539693 27400 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W0126 16:17:00.545255 27400 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    main()
  File "main.py", line 124, in main
    test_model(cfg, weights=args.weights, parallel=parallel)
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/home/yxs/PaddleVideo-develop/paddlevideo/tasks/test.py", line 88, in test_model
    outputs = model(data, mode='test')
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/yxs/PaddleVideo-develop/paddlevideo/modeling/framework/recognizers/base.py", line 53, in forward
    return self.test_step(data_batch)
  File "/home/yxs/PaddleVideo-develop/paddlevideo/modeling/framework/recognizers/recognizer_transformer_MRI.py", line 68, in test_step
    num_views = imgs.shape[3] // self.backbone.seg_num
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1123, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'VisionTransformer' object has no attribute 'seg_num'
请教各位，训练过程没问题，测试过程 报属性错误

**Comment by yxs96** [comment]
训练使用的是PP-Care中的Timesformer模型，训练过程无问题，测试过程报错
测试代码：
python main.py -c applications/PP-Care/configs/timesformer_MRI.yaml --test -w "./output/TimeSformer_MRI/TimeSformer_MRI_best.pdparams"
报错：
AttributeError: 'VisionTransformer' object has no attribute 'seg_num'
自己排错是recognizer_transformer_MRI.py文件中 self.backbone.seg_num无seg_num属性，但yaml文件中有该参数
请问应该如何修改代码呢？

**Comment by huangjun12** [comment]
需要将yaml文件中的seg_num改成num_seg

**Comment by yxs96** [comment]
@huangjun12 非常感谢您的指点，旧问题已解决。yaml文件已改，且将recognizer_transformer_MRI.py中test_step函数的seg_num改为num_seg，但产生了新问题：AssertionError: Input image size (8*224) doesn't match model (224*224).
自己排错是recognizer_transformer_MRI.py中test_step函数中的for循环中view的维度不对应vit.py中的维度，仍未解决
希望等得到您的进一步指点

**Comment by yxs96** [comment]
CUDA_VISIBLE_DEVICES=2 python main.py -c applications/PP-Care/configs/timesformer_MRI_wr.yaml --test -w "./output/TimeSformer_MRI_8/TimeSformer_MRI_best.pdparams" 
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:24: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:25: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:26: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:27: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:28: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
/home/yxs/PaddleVideo-develop/paddlevideo/loader/pipelines/augmentations_ava.py:29: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
Warning! No module named 'paddlenlp', [paddlenlp] package and it's dependencies is required for ActBERT.
Warning! No module named 'lmdb', [lmdb] package and it's dependencies is required for ActBERT.
Warning! No module named 'paddlenlp', [paddlenlp] package and it's dependencies is required for ActBERT.
Warning! No module named 'lmdb', [lmdb] package and it's dependencies is required for ActBERT.
Warning! No module named 'paddlenlp', [paddlenlp] package and it's dependencies is required for ActBERT.
[01/31 14:55:13] DATASET : 
[01/31 14:55:13]     batch_size : 4
[01/31 14:55:13]     num_workers : 4
[01/31 14:55:13]     test : 
[01/31 14:55:13]         data_prefix : 
[01/31 14:55:13]         file_path : /home/yxs/PaddleVideo-develop/data/PP-Care/datasets/AV133/wrtest_res3.txt
[01/31 14:55:13]         format : MRIDataset
[01/31 14:55:13]     test_batch_size : 4
[01/31 14:55:13]     train : 
[01/31 14:55:13]         data_prefix : 
[01/31 14:55:13]         file_path : /home/yxs/PaddleVideo-develop/data/PP-Care/datasets/AV133/wrtrain_res3.txt
[01/31 14:55:13]         format : MRIDataset
[01/31 14:55:13]     valid : 
[01/31 14:55:13]         data_prefix : 
[01/31 14:55:13]         file_path : /home/yxs/PaddleVideo-develop/data/PP-Care/datasets/AV133/wrtest_res3.txt
[01/31 14:55:13]         format : MRIDataset
[01/31 14:55:13] ------------------------------------------------------------
[01/31 14:55:13] GRADIENT_ACCUMULATION : 
[01/31 14:55:13]     global_batch_size : 64
[01/31 14:55:13] ------------------------------------------------------------
[01/31 14:55:13] METRIC : 
[01/31 14:55:13]     name : CenterCropMetric_MRI
[01/31 14:55:13] ------------------------------------------------------------
[01/31 14:55:13] MODEL : 
[01/31 14:55:13]     backbone : 
[01/31 14:55:13]         attention_type : divided_space_time
[01/31 14:55:13]         depth : 12
[01/31 14:55:13]         embed_dim : 768
[01/31 14:55:13]         epsilon : 1e-06
[01/31 14:55:13]         img_size : 224
[01/31 14:55:13]         in_channels : 1
[01/31 14:55:13]         mlp_ratio : 4
[01/31 14:55:13]         name : VisionTransformer
[01/31 14:55:13]         num_heads : 12
[01/31 14:55:13]         num_seg : 8
[01/31 14:55:13]         patch_size : 16
[01/31 14:55:13]         pretrained : /home/yxs/PaddleVideo-develop/data/PP-Care/ViT_base_patch16_224_pretrained.pdparams
[01/31 14:55:13]         qkv_bias : True
[01/31 14:55:13]     framework : RecognizerTransformer_MRI
[01/31 14:55:13]     head : 
[01/31 14:55:13]         in_channels : 768
[01/31 14:55:13]         name : TimeSformerHead
[01/31 14:55:13]         num_classes : 2
[01/31 14:55:13]         std : 0.02
[01/31 14:55:13] ------------------------------------------------------------
[01/31 14:55:13] OPTIMIZER : 
[01/31 14:55:13]     learning_rate : 
[01/31 14:55:13]         gamma : 0.9
[01/31 14:55:13]         learning_rate : 0.005
[01/31 14:55:13]         milestones : [20, 29]
[01/31 14:55:13]         name : MultiStepDecay
[01/31 14:55:13]     name : Adam
[01/31 14:55:13]     weight_decay : 
[01/31 14:55:13]         name : L2
[01/31 14:55:13]         value : 5e-05
[01/31 14:55:13] ------------------------------------------------------------
[01/31 14:55:13] PIPELINE : 
[01/31 14:55:13]     test : 
[01/31 14:55:13]         decode : 
[01/31 14:55:13]             name : MRIDecoder
[01/31 14:55:13]         sample : 
[01/31 14:55:13]             linspace_sample : True
[01/31 14:55:13]             name : Sampler
[01/31 14:55:13]             num_seg : 8
[01/31 14:55:13]             seg_len : 1
[01/31 14:55:13]             valid_mode : True
[01/31 14:55:13]     train : 
[01/31 14:55:13]         decode : 
[01/31 14:55:13]             name : MRIDecoder
[01/31 14:55:13]         sample : 
[01/31 14:55:13]             linspace_sample : True
[01/31 14:55:13]             name : Sampler
[01/31 14:55:13]             num_seg : 8
[01/31 14:55:13]             seg_len : 1
[01/31 14:55:13]             valid_mode : False
[01/31 14:55:13]     valid : 
[01/31 14:55:13]         decode : 
[01/31 14:55:13]             name : MRIDecoder
[01/31 14:55:13]         sample : 
[01/31 14:55:13]             linspace_sample : True
[01/31 14:55:13]             name : Sampler
[01/31 14:55:13]             num_seg : 8
[01/31 14:55:13]             seg_len : 1
[01/31 14:55:13]             valid_mode : False
[01/31 14:55:13] ------------------------------------------------------------
[01/31 14:55:13] epochs : 30
[01/31 14:55:13] log_interval : 20
[01/31 14:55:13] log_level : INFO
[01/31 14:55:13] model_name : TimeSformer_MRI
[01/31 14:55:13] save_interval : 5
W0131 14:55:13.379593 38730 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W0131 14:55:13.384462 38730 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
********************************************
imgs.shape =  [4, 8, 224, 224]
num_views = 224
0
view.shape =  [4, 8, 8, 224]
**********************
x.shape =   [4, 1, 8, 8, 224]
224
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    main()
  File "main.py", line 124, in main
    test_model(cfg, weights=args.weights, parallel=parallel)
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/home/yxs/PaddleVideo-develop/paddlevideo/tasks/test.py", line 88, in test_model
    outputs = model(data, mode='test')
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/yxs/PaddleVideo-develop/paddlevideo/modeling/framework/recognizers/base.py", line 53, in forward
    return self.test_step(data_batch)
  File "/home/yxs/PaddleVideo-develop/paddlevideo/modeling/framework/recognizers/recognizer_transformer_MRI.py", line 79, in test_step
    cls_score.append(self.forward_net(view))
  File "/home/yxs/PaddleVideo-develop/paddlevideo/modeling/framework/recognizers/recognizer_transformer_MRI.py", line 32, in forward_net
    feature = self.backbone(imgs)
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/yxs/PaddleVideo-develop/paddlevideo/modeling/backbones/vit.py", line 466, in forward
    x = self.forward_features(x)
  File "/home/yxs/PaddleVideo-develop/paddlevideo/modeling/backbones/vit.py", line 400, in forward_features
    x, T, W = self.patch_embed(x)  # [BT,nH*nW,F]
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/yxs/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/yxs/PaddleVideo-develop/paddlevideo/modeling/backbones/vit.py", line 284, in forward
    f"Input image size ({H}*{W}) doesn't match model ({self.img_size[0]}*{self.img_size[1]})."
AssertionError: Input image size (8*224) doesn't match model (224*224).

**Comment by yxs96** [comment]
def test_step(self, data_batch):
        """Define how the model is going to infer, from input to output."""
        #print("test********************************************")
        imgs = data_batch[0]
        #print("test's imgs.shape = ", imgs.shape) # [4, 8, 224, 224]：4表示测试时的batch_size
 
        num_views = imgs.shape[2]     # self.backbone.seg_num
        #print("num_views =", num_views)
        cls_score = self.forward_net(imgs)
        return cls_score
        #cls_score = []
        #for i in range(num_views):
            #print(i)
            #view = imgs[:, :,  i * self.backbone.num_seg:(i + 1) * self.backbone.num_seg]
            #cls_score.append(self.forward_net(view))
        #cls_score = self.average_view(cls_score)
        #return cls_score
注释掉下面的代码即可（已解决）
