### ISSUE TITLE
训练stgcn模型问题：环境问题

### ISSUE THREAD

**Issue by Bradly-s** [PaddlePaddle/PaddleVideo#643]
**paddle版本为develop版本**

**报错信息如下**：
[08/31 21:47:28] model_name : STGCN
W0831 21:47:29.443328 4185452 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W0831 21:47:29.455291 4185452 gpu_resources.cc:149] device: 0, cuDNN Version: 8.6.
[08/31 21:47:29] Loading data, it will take some moment...
[08/31 21:47:29] Data Loaded!
[08/31 21:47:29] Loading data, it will take some moment...
[08/31 21:47:30] Data Loaded!
[08/31 21:47:30] Training in fp32 mode.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 10. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 10. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 10. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 10. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 10. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 10. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 10. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 10. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 10. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 10. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 11. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 11. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 11. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 11. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 11. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 11. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 11. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 11. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 11. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 11. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 21. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 23. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 23. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 23. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 23. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 23. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 23. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 23. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 23. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 23. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 23. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 22. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 26. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 13. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 10, or == -100, but got 19. Please check label value.
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    main()
  File "main.py", line 139, in main
    profiler_options=args.profiler_options)
  File "PaddleVideo/paddlevideo/tasks/train.py", line 237, in train_model
    outputs = model(data, mode='train')
  File "/home/dp504/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1240, in __call__
    return self.forward(*inputs, **kwargs)
  File "PaddleVideo/paddlevideo/modeling/framework/recognizers/base.py", line 49, in forward
    return self.train_step(data_batch)
  File "PaddleVideo/paddlevideo/modeling/framework/recognizers/recognizer_gcn.py", line 54, in train_step
    loss_metrics = self.head.loss(cls_score, label, if_top5=self.if_top5)
  File "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleVideo/paddlevideo/modeling/heads/base.py", line 85, in loss
    loss = self.loss_func(scores, labels, **kwargs)
  File "/home/dp504/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1240, in __call__
    return self.forward(*inputs, **kwargs)
  File "PaddleVideo/paddlevideo/modeling/losses/base.py", line 49, in forward
    return self._forward(*args, **kwargs) * self.loss_weight
  File "PaddleVideo/paddlevideo/modeling/losses/cross_entropy_loss.py", line 35, in _forward
    loss = F.cross_entropy(score, labels, **kwargs)
  File "/home/dp504/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 2788, in cross_entropy
    if paddle.count_nonzero(is_ignore) > 0:  # ignore label
  File "/home/dp504/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/tensor_patch_methods.py", line 681, in __bool__
    return self.__nonzero__()
  File "/home/dp504/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/tensor_patch_methods.py", line 678, in __nonzero__
    return bool(np.array(self) > 0)
  File "/home/dp504/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/tensor_patch_methods.py", line 704, in __array__
    array = self.numpy(False)
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ../paddle/phi/backends/gpu/cuda/cuda_info.cc:272)

[1]+  Killed                  python

**Comment by Nanh1860** [comment]
i got similar error, any help?
error:
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1010 Assertion `false` failed. The value of label expected >= 0 and < 9, or == -100, but got 9. Please check label value.
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Jupyter_file\PaddleOCR\tools\train.py", line 211, in <module>
    main(config, device, logger, vdl_writer)
  File "C:\Users\Administrator\Downloads\Jupyter_file\PaddleOCR\tools\train.py", line 183, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "C:\Users\Administrator\Downloads\Jupyter_file\PaddleOCR\tools\program.py", line 304, in train
    loss = loss_class(preds, batch)
  File "C:\Users\Administrator\anaconda3\envs\fpt\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\Administrator\Downloads\Jupyter_file\PaddleOCR\ppocr\losses\vqa_token_layoutlm_loss.py", line 41, in forward
    loss = self.loss_class(active_output, active_label)
  File "C:\Users\Administrator\anaconda3\envs\fpt\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\fpt\lib\site-packages\paddle\nn\layer\loss.py", line 373, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "C:\Users\Administrator\anaconda3\envs\fpt\lib\site-packages\paddle\nn\functional\loss.py", line 2790, in cross_entropy
    if paddle.count_nonzero(is_ignore) > 0:  # ignore label
  File "C:\Users\Administrator\anaconda3\envs\fpt\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 673, in __bool__
    return self.__nonzero__()
  File "C:\Users\Administrator\anaconda3\envs\fpt\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 670, in __nonzero__
    return bool(np.array(self) > 0)
  File "C:\Users\Administrator\anaconda3\envs\fpt\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 696, in __array__
    array = self.numpy(False)
OSError: (External) CUDA error(719), unspecified launch failure.
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:267)
