### ISSUE TITLE
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by Bradly-s** [PaddlePaddle/PaddleVideo#654]
paddlepaddle-gpu版本：   0.0.0.post102
PaddleVideo版本：develop
————以下是报错信息——————————————————————————————————
(paddledevelop) C:\Users\swf>python
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: D:\Program Files\miniconda3\envs\paddledevelop\lib\site-packages\paddle\fluid\libpaddle.pyd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\miniconda3\envs\paddledevelop\lib\site-packages\paddle\__init__.py", line 27, in <module>
    from .framework import monkey_patch_variable
  File "D:\Program Files\miniconda3\envs\paddledevelop\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "D:\Program Files\miniconda3\envs\paddledevelop\lib\site-packages\paddle\framework\random.py", line 17, in <module>
    from paddle import fluid
  File "D:\Program Files\miniconda3\envs\paddledevelop\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "D:\Program Files\miniconda3\envs\paddledevelop\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "D:\Program Files\miniconda3\envs\paddledevelop\lib\site-packages\paddle\fluid\core.py", line 355, in <module>
    raise e
  File "D:\Program Files\miniconda3\envs\paddledevelop\lib\site-packages\paddle\fluid\core.py", line 269, in <module>
    from . import libpaddle
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。
>>>

**Comment by westfish** [comment]
根据你提供的错误信息，问题出在尝试导入PaddlePaddle时，无法加载DLL，这可能是由于你的环境与PaddlePaddle的版本不兼容，可以尝试安装其他Paddle版本

另外，如果有图像、视频理解和生成的需求，可以使用我们新的跨模态工具: https://github.com/PaddlePaddle/PaddleMIX/tree/develop
