### ISSUE TITLE
data/VideoTag_test.list not exist, please check the data list

### ISSUE THREAD

**Issue by Wei-Wu233** [PaddlePaddle/PaddleVideo#659]
D:\ProgramData\anaconda\envs\paddle\python.exe E:\code\PaddleVideo-develop\applications\VideoTag\videotag_test.py 
Namespace(extractor_config='configs/tsn.yaml', extractor_name='TSN', extractor_weights='weights/tsn', filelist='data/VideoTag_test.list', label_file='label_3396.txt', predictor_config='configs/attention_lstm.yaml', predictor_name='AttentionLSTM', predictor_weights='weights/attention_lstm', save_dir='data/VideoTag_results', use_gpu=True)
[INFO: videotag_test.py:  236]: Namespace(extractor_config='configs/tsn.yaml', extractor_name='TSN', extractor_weights='weights/tsn', filelist='data/VideoTag_test.list', label_file='label_3396.txt', predictor_config='configs/attention_lstm.yaml', predictor_name='AttentionLSTM', predictor_weights='weights/attention_lstm', save_dir='data/VideoTag_results', use_gpu=True)
I1204 17:37:06.475123 31128 interpretercore.cc:237] New Executor is Running.
W1204 17:37:06.477123 31128 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 11.6
W1204 17:37:06.482126 31128 gpu_resources.cc:149] device: 0, cuDNN Version: 8.2.
[INFO: videotag_test.py:  129]: load extractor weights from weights/tsn
[INFO: tsn.py:  154]: Load pretrain weights from weights/tsn, exclude fc layer.
===pretrain=== weights/tsn
Traceback (most recent call last):
  File "E:\code\PaddleVideo-develop\applications\VideoTag\videotag_test.py", line 237, in <module>
    main()
  File "E:\code\PaddleVideo-develop\applications\VideoTag\videotag_test.py", line 137, in main
    extractor_reader = get_reader(args.extractor_name, 'infer',
  File "E:\code\PaddleVideo-develop\applications\VideoTag\reader\reader_utils.py", line 80, in get_reader
    return reader_model.create_reader()
  File "E:\code\PaddleVideo-develop\applications\VideoTag\reader\kinetics_reader.py", line 109, in create_reader
    assert os.path.exists(self.filelist), \
AssertionError: data/VideoTag_test.list not exist, please check the data list

Process finished with exit code 1

我这边调用VideoTag_test.py运行，但是data文件里缺少list文件

**Comment by westfish** [comment]
首先，确保data/VideoTag_test.list文件确实存在于你的文件系统中，并且路径是正确的。根据错误信息，脚本期望在data目录下找到名为VideoTag_test.list的文件。
如果这个文件不存在，你需要创建一个。这个文件应该包含你想要用于视频标签测试的所有视频文件的路径，格式通常是每行一个视频文件的相对或绝对路径。例如：
E:/path/to/video1.mp4
E:/path/to/video2.mp4

另外，如果有图像、视频理解和生成的需求，可以使用我们新的跨模态工具: https://github.com/PaddlePaddle/PaddleMIX/tree/develop
