### ISSUE TITLE
PaddleServing Inference

### ISSUE THREAD

**Issue by ShahZebYousafzai** [PaddlePaddle/PaddleVideo#668]
When running

`python recognition_web_service.py -n PPTSM -c configs/PP-TSM.yaml`

Nothing happens and the code just exits.

Then I changed

`uci_service = VideoService(name="video")`
` uci_service.get_pipeline_response(read_op=args.config)`
` uci_service.run_service()`

to 

`web = WebService()`
 `web.get_pipeline_response(read_op=args.config)`
 `web.run_service()`
 
 After some changes I get the following error
 
 `Traceback (most recent call last):
  File "recognition_web_service.py", line 206, in <module>
    web.run_service()
  File "C:\Users\UMAIR COMPUTER\anaconda3\envs\paddle_env\lib\site-packages\paddle_serving_server\web_service.py", line 69, in run_service
    self._server.run_server()
  File "C:\Users\UMAIR COMPUTER\anaconda3\envs\paddle_env\lib\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 292, in run_server
    if self._build_dag_each_worker:
AttributeError: 'PipelineServer' object has no attribute '_build_dag_each_worker'`

**Comment by westfish** [comment]
你好，根据你提供的错误信息，问题出在pipeline_server.py文件的第292行，这里的self._build_dag_each_worker在PipelineServer对象中并不存在。这可能是因为你的Paddle Serving版本和你的代码不兼容。

另外，如果有图像、视频理解和生成的需求，可以使用我们新的跨模态工具: https://github.com/PaddlePaddle/PaddleMIX/tree/develop
