### ISSUE TITLE
ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.

### ISSUE THREAD

**Issue by savior7w** [PaddlePaddle/PaddleVideo#84]
This is the log!

INFO 2021-01-21 17:49:12,814 launch_utils.py:476] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log.
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    main()
  File "main.py", line 54, in main
    cfg = get_config(args.config, overrides=args.override)
  File "/home/AI/tmp/paddle/PaddleVideo/paddlevideo/utils/config.py", line 169, in get_config
    config = parse_config(fname)
  File "/home/AI/tmp/paddle/PaddleVideo/paddlevideo/utils/config.py", line 53, in parse_config
    yaml_config = AttrDict(yaml.load(fopen, Loader=yaml.SafeLoader))
  File "/root/anaconda3/envs/head/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/root/anaconda3/envs/head/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/root/anaconda3/envs/head/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/root/anaconda3/envs/head/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/root/anaconda3/envs/head/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/root/anaconda3/envs/head/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/root/anaconda3/envs/head/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/root/anaconda3/envs/head/lib/python3.7/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "./configs/example.yaml", line 2, column 1
expected <block end>, but found '<block mapping start>'
  in "./configs/example.yaml", line 4, column 5
INFO 2021-01-21 17:49:18,857 launch_utils.py:308] terminate all the procs
ERROR 2021-01-21 17:49:18,857 launch_utils.py:546] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-01-21 17:49:21,861 launch_utils.py:308] terminate all the procs

**Comment by huangjun12** [comment]
看起来是配置文件不对，这是训练什么模型呢

**Comment by savior7w** [comment]
> 看起来是配置文件不对，这是训练什么模型呢

ucf101,我把ucf101数据集只保留第一个类别训练，example.yaml需要类别改成1吗？

**Comment by huangjun12** [comment]
example.yaml配置文件不一定能跑通

你可以参考下
https://github.com/PaddlePaddle/PaddleVideo/blob/main/run.sh 这个文件和[文档](https://github.com/PaddlePaddle/PaddleVideo/blob/main/docs/zh-CN/model_zoo/recognition/tsn.md)
跑tsm模型试试

**Comment by savior7w** [comment]
用脚本跑过了，报这个错误
-----------  Configuration Arguments -----------
gpus: 0,1,2,3
heter_worker_num: None
heter_workers:
http_port: None
ips: 127.0.0.1
log_dir: log_pptsm
nproc_per_node: None
server_num: None
servers:
training_script: main.py
training_script_args: ['--validate', '-c', 'configs/recognition/tsm/pptsm.yaml', '-o', 'log_level=INFO']
worker_num: None
workers:
------------------------------------------------
WARNING 2021-01-22 09:07:42,005 launch.py:314] Not found distinct arguments and compiled with cuda. Default use collective mode
launch train in GPU mode
INFO 2021-01-22 09:07:42,006 launch_utils.py:583] Change selected_gpus into reletive values. --ips:0,1,2,3 will change into relative_ips:[0, 1, 2, 3] according to your CUDA_VISIBLE_DEVICES:['0', '1', '2', '3', '4', '5', '6', '7']
INFO 2021-01-22 09:07:42,006 launch_utils.py:472] Local start 4 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:57381               |
    |                     PADDLE_TRAINERS_NUM                        4                      |
    |                PADDLE_TRAINER_ENDPOINTS  ... 0.1:56241,127.0.0.1:46379,127.0.0.1:51469|
    |                     FLAGS_selected_gpus                        0                      |
    +=======================================================================================+

INFO 2021-01-22 09:07:42,007 launch_utils.py:476] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log_pptsm/endpoints.log.
已杀死

**Comment by savior7w** [comment]
> example.yaml配置文件不一定能跑通
> 
> 你可以参考下
> https://github.com/PaddlePaddle/PaddleVideo/blob/main/run.sh 这个文件和[文档](https://github.com/PaddlePaddle/PaddleVideo/blob/main/docs/zh-CN/model_zoo/recognition/tsn.md)
> 跑tsm模型试试

 用脚本跑了，也报这个错误
-----------  Configuration Arguments -----------
gpus: 0
heter_worker_num: None
heter_workers:
http_port: None
ips: 127.0.0.1
log_dir: log_pptsm
nproc_per_node: None
server_num: None
servers:
training_script: main.py
training_script_args: ['--validate', '-c', 'configs/recognition/tsm/pptsm.yaml', '-o', 'log_level=INFO']
worker_num: None
workers:
------------------------------------------------
WARNING 2021-01-22 09:14:35,019 launch.py:314] Not found distinct arguments and compiled with cuda. Default use collective mode
launch train in GPU mode
INFO 2021-01-22 09:14:35,020 launch_utils.py:583] Change selected_gpus into reletive values. --ips:0 will change into relative_ips:[0] according to your CUDA_VISIBLE_DEVICES:['0', '1', '2', '3', '4', '5', '6', '7']
INFO 2021-01-22 09:14:35,020 launch_utils.py:472] Local start 1 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:38125               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:38125               |
    |                     FLAGS_selected_gpus                        0                      |
    +=======================================================================================+

INFO 2021-01-22 09:14:35,021 launch_utils.py:476] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log_pptsm/endpoints.log.
[01/22 09:14:36] DATASET :
[01/22 09:14:36]     batch_size : 16
[01/22 09:14:36]     num_workers : 4
[01/22 09:14:36]     test :
[01/22 09:14:36]         data_prefix :
[01/22 09:14:36]         file_path : data/dataset/ucf101/ucf101_val_split_1_rawframes.txt
[01/22 09:14:36]         format : FrameDataset
[01/22 09:14:36]         suffix : img_{:05}.jpg
[01/22 09:14:36]     train :
[01/22 09:14:36]         data_prefix :
[01/22 09:14:36]         file_path : data/dataset/ucf101/ucf101_train_split_1_rawframes.txt
[01/22 09:14:36]         format : FrameDataset
[01/22 09:14:36]         suffix : img_{:05}.jpg
[01/22 09:14:36]     valid :
[01/22 09:14:36]         data_prefix :
[01/22 09:14:36]         file_path : data/dataset/ucf101/ucf101_val_split_1_rawframes.txt
[01/22 09:14:36]         format : FrameDataset
[01/22 09:14:36]         suffix : img_{:05}.jpg
[01/22 09:14:36] ------------------------------------------------------------
[01/22 09:14:36] METRIC :
[01/22 09:14:36]     name : CenterCropMetric
[01/22 09:14:36] ------------------------------------------------------------
[01/22 09:14:36] MODEL :
[01/22 09:14:36]     backbone :
[01/22 09:14:36]         depth : 50
[01/22 09:14:36]         name : ResNetTweaksTSM
[01/22 09:14:36]         num_seg : 8
[01/22 09:14:36]         pretrained : ./ResNet50_vd_ssld_v2_pretrained.pdparams
[01/22 09:14:36]     framework : Recognizer2D
[01/22 09:14:36]     head :
[01/22 09:14:36]         drop_ratio : 0.5
[01/22 09:14:36]         in_channels : 2048
[01/22 09:14:36]         name : TSMHead
[01/22 09:14:36]         num_classes : 101
[01/22 09:14:36]         std : 0.01
[01/22 09:14:36] ------------------------------------------------------------
[01/22 09:14:36] OPTIMIZER :
[01/22 09:14:36]     learning_rate :
[01/22 09:14:36]         boundaries : [40, 60]
[01/22 09:14:36]         name : PiecewiseDecay
[01/22 09:14:36]         values : [0.01, 0.001, 0.0001]
[01/22 09:14:36]     momentum : 0.9
[01/22 09:14:36]     name : Momentum
[01/22 09:14:36]     weight_decay :
[01/22 09:14:36]         name : L2
[01/22 09:14:36]         value : 0.0002
[01/22 09:14:36] ------------------------------------------------------------
[01/22 09:14:36] PIPELINE :
[01/22 09:14:36]     test :
[01/22 09:14:36]         decode :
[01/22 09:14:36]             name : FrameDecoder
[01/22 09:14:36]         sample :
[01/22 09:14:36]             name : Sampler
[01/22 09:14:36]             num_seg : 8
[01/22 09:14:36]             seg_len : 1
[01/22 09:14:36]             valid_mode : True
[01/22 09:14:36]         transform :
[01/22 09:14:36]             Scale :
[01/22 09:14:36]                 short_size : 256
[01/22 09:14:36]             CenterCrop :
[01/22 09:14:36]                 target_size : 224
[01/22 09:14:36]             Image2Array : None
[01/22 09:14:36]             Normalization :
[01/22 09:14:36]                 mean : [0.485, 0.456, 0.406]
[01/22 09:14:36]                 std : [0.229, 0.224, 0.225]
[01/22 09:14:36]     train :
[01/22 09:14:36]         decode :
[01/22 09:14:36]             name : FrameDecoder
[01/22 09:14:36]         sample :
[01/22 09:14:36]             name : Sampler
[01/22 09:14:36]             num_seg : 8
[01/22 09:14:36]             seg_len : 1
[01/22 09:14:36]             valid_mode : False
[01/22 09:14:36]         transform :
[01/22 09:14:36]             Scale :
[01/22 09:14:36]                 short_size : 256
[01/22 09:14:36]             MultiScaleCrop :
[01/22 09:14:36]                 target_size : 256
[01/22 09:14:36]             RandomCrop :
[01/22 09:14:36]                 target_size : 224
[01/22 09:14:36]             RandomFlip : None
[01/22 09:14:36]             Image2Array : None
[01/22 09:14:36]             Normalization :
[01/22 09:14:36]                 mean : [0.485, 0.456, 0.406]
[01/22 09:14:36]                 std : [0.229, 0.224, 0.225]
[01/22 09:14:36]     valid :
[01/22 09:14:36]         decode :
[01/22 09:14:36]             name : FrameDecoder
[01/22 09:14:36]         sample :
[01/22 09:14:36]             name : Sampler
[01/22 09:14:36]             num_seg : 8
[01/22 09:14:36]             seg_len : 1
[01/22 09:14:36]             valid_mode : True
[01/22 09:14:36]         transform :
[01/22 09:14:36]             Scale :
[01/22 09:14:36]                 short_size : 256
[01/22 09:14:36]             CenterCrop :
[01/22 09:14:36]                 target_size : 224
[01/22 09:14:36]             Image2Array : None
[01/22 09:14:36]             Normalization :
[01/22 09:14:36]                 mean : [0.485, 0.456, 0.406]
[01/22 09:14:36]                 std : [0.229, 0.224, 0.225]
[01/22 09:14:36] ------------------------------------------------------------
[01/22 09:14:36] PRECISEBN :
[01/22 09:14:36]     num_iters_preciseBN : 80
[01/22 09:14:36]     preciseBN_interval : 5
[01/22 09:14:36] ------------------------------------------------------------
[01/22 09:14:36] epochs : 80
[01/22 09:14:36] log_interval : 20
[01/22 09:14:36] log_level : INFO
[01/22 09:14:36] model_name : ppTSM
[01/22 09:14:36] resume_from :
W0122 09:14:36.216168 99413 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0122 09:14:36.221127 99413 device_context.cc:330] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    main()
  File "main.py", line 69, in main
    validate=args.validate)
  File "/home/AI/tmp/paddle/PaddleVideo/paddlevideo/tasks/train.py", line 51, in train_model
    model = build_model(cfg.MODEL)
  File "/home/AI/tmp/paddle/PaddleVideo/paddlevideo/modeling/builder.py", line 48, in build_model
    return build_recognizer(cfg)
  File "/home/AI/tmp/paddle/PaddleVideo/paddlevideo/modeling/builder.py", line 36, in build_recognizer
    return build(cfg, RECOGNIZERS, key='framework')
  File "/home/AI/tmp/paddle/PaddleVideo/paddlevideo/utils/build_utils.py", line 35, in build
    return obj_cls(**cfg_copy)
  File "/home/AI/tmp/paddle/PaddleVideo/paddlevideo/modeling/framework/recognizers/base.py", line 28, in __init__
    self.backbone.init_weights()
  File "/home/AI/tmp/paddle/PaddleVideo/paddlevideo/modeling/backbones/resnet_tweaks_tsm.py", line 299, in init_weights
    load_ckpt(self, self.pretrained)
  File "/home/AI/tmp/paddle/PaddleVideo/paddlevideo/utils/dist_utils.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/AI/tmp/paddle/PaddleVideo/paddlevideo/utils/save_load.py", line 34, in load_ckpt
    raise IOError(f'{weight_path} is not a checkpoint file')
OSError: ./ResNet50_vd_ssld_v2_pretrained.pdparams is not a checkpoint file
INFO 2021-01-22 09:14:47,068 launch_utils.py:308] terminate all the procs
ERROR 2021-01-22 09:14:47,069 launch_utils.py:546] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-01-22 09:14:50,072 launch_utils.py:308] terminate all the procs

**Comment by huangjun12** [comment]
看报错是没有下载预训练模型， https://github.com/PaddlePaddle/PaddleVideo/blob/main/docs/zh-CN/model_zoo/recognition/tsn.md 您可以参考这个文档操作下
